# Colab

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!pwd

/content


In [3]:
cd /content/drive/MyDrive/PythonProjects/skgnmda

/content/drive/MyDrive/PythonProjects/skgnmda


# Prerequirments

In [4]:
!pwd

/content/drive/MyDrive/PythonProjects/skgnmda


In [5]:
dataset = 'mdkg_hmdad'

# Read Examples and Clean It

In [6]:
from src.config import PROCESSED_DATA_DIR, ENTITY_VOCAB_TEMPLATE
from src.utils import format_filename, pickle_load

entity_vocab_path = format_filename(PROCESSED_DATA_DIR, ENTITY_VOCAB_TEMPLATE, dataset=dataset)
entity_vocab = pickle_load(entity_vocab_path)

Logging Info - Loaded: /content/drive/MyDrive/PythonProjects/skgnmda/data_repository/processed/mdkg_hmdad_entity_vocab.pkl


In [7]:
len(entity_vocab)

66911

In [8]:
from src.config import DISEASE_MICROBE_EXAMPLE, PROCESSED_DATA_DIR
from src.utils import format_filename
import numpy as np

examples_file = format_filename(
    PROCESSED_DATA_DIR, DISEASE_MICROBE_EXAMPLE, dataset=dataset
)
examples = np.load(examples_file)

# Generate Gaussian Similarity

In [9]:
from src.methods.similarity_metrics.gaussian_similarity import get_gaussian_similarity

train_ds, train_ms, test_ds, test_ms = get_gaussian_similarity(examples, examples[[100], :])

first_term2id= {64642: 0, 1667: 1, 50436: 2, 48777: 3, 10506: 4, 33293: 5, 654: 6, 30861: 7, 11153: 8, 64149: 9, 61336: 10, 63129: 11, 13213: 12, 55164: 13, 40873: 14, 34347: 15, 50863: 16, 59444: 17, 22068: 18, 3127: 19, 44991: 20, 66623: 21, 4928: 22, 25026: 23, 7877: 24, 200: 25, 44112: 26, 31069: 27, 54370: 28, 20066: 29, 43621: 30, 66282: 31, 43372: 32, 28016: 33, 12403: 34, 45301: 35, 37496: 36, 9724: 37, 13565: 38} second_term2id= {24065: 0, 19458: 1, 40449: 2, 30212: 3, 12808: 4, 50698: 5, 20492: 6, 46605: 7, 5135: 8, 37392: 9, 42514: 10, 20153: 11, 12824: 12, 37400: 13, 8218: 14, 1049: 15, 30750: 16, 48672: 17, 56353: 18, 52770: 19, 31268: 20, 46117: 21, 10276: 22, 59432: 23, 57903: 24, 2097: 25, 24627: 26, 29241: 27, 50234: 28, 19514: 29, 9788: 30, 14909: 31, 8766: 32, 60987: 33, 64571: 34, 35905: 35, 27202: 36, 26183: 37, 4683: 38, 44108: 39, 33867: 40, 7246: 41, 42577: 42, 61523: 43, 3157: 44, 12374: 45, 3669: 46, 5718: 47, 6745: 48, 64598: 49, 51285: 50, 25176: 51, 35933: 

In [10]:
train_ds.shape

(897, 39)

In [11]:
train_ms.shape

(897, 291)

In [12]:
test_ds.shape

(1, 39)

In [13]:
test_ms.shape

(1, 291)

In [14]:
examples[0]

array([50863, 33211,     1])

In [15]:
train_ds[7] - train_ds[2]

array([-0.00452821, -0.00452821, -0.00348749, -0.00641437, -0.00380446,
       -0.99999986, -0.00268567, -0.00415068, -0.00452821, -0.00452812,
       -0.0053894 , -0.00452821, -0.00538882, -0.00452821, -0.00319668,
       -0.00452821, -0.00122691, -0.00538916, -0.00452821, -0.00452821,
       -0.00415068, -0.00268587, -0.00452821, -0.00452812, -0.00587969,
       -0.00452821, -0.00494007, -0.0041506 , -0.00293011, -0.00415038,
        0.99999986, -0.00538929, -0.00452821, -0.0053894 , -0.0017381 ,
       -0.00452821, -0.00452821, -0.00452812, -0.00452821])

In [16]:
examples[0:10, :]

array([[50863, 33211,     1],
       [43621, 40832,     1],
       [33293, 47880,     1],
       [13213, 53186,     1],
       [33293, 14909,     1],
       [33293, 35937,     1],
       [12403, 26565,     1],
       [43621, 57454,     1],
       [43621, 63599,     1],
       [43621, 14120,     1]])

In [17]:
test_ms

array([[5.22278885e-01, 5.22278885e-01, 5.22278885e-01, 5.22278885e-01,
        2.72775234e-01, 2.72775234e-01, 5.22278885e-01, 5.22278885e-01,
        5.22278885e-01, 5.22278885e-01, 5.22278885e-01, 5.22278885e-01,
        5.22278885e-01, 5.22278885e-01, 5.22278885e-01, 5.22278885e-01,
        5.22278885e-01, 5.22278885e-01, 5.22278885e-01, 7.44063281e-02,
        2.02962035e-02, 2.72775234e-01, 5.22278885e-01, 5.22278885e-01,
        2.72775234e-01, 5.22278885e-01, 5.22278885e-01, 3.88608541e-02,
        5.22278885e-01, 5.22278885e-01, 2.72775234e-01, 5.22278885e-01,
        5.22278885e-01, 5.22278885e-01, 5.22278885e-01, 2.02962035e-02,
        5.22278885e-01, 2.72775234e-01, 5.22278885e-01, 5.22278885e-01,
        5.22278885e-01, 5.22278885e-01, 2.72775234e-01, 5.22278885e-01,
        5.22278885e-01, 5.22278885e-01, 5.22278885e-01, 2.72775234e-01,
        5.22278885e-01, 5.22278885e-01, 5.22278885e-01, 5.22278885e-01,
        5.22278885e-01, 5.22278885e-01, 5.22278885e-01, 2.727752